"""add delete orphan

Revision ID: 14589fbfa1b1
Revises: d305912758c4
Create Date: 2018-05-17 11:47:59.674519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14589fbfa1b1'
down_revision = 'd305912758c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
