"""create new accociation table

Revision ID: 9234fff1ed1f
Revises: fe2ef0f61b41
Create Date: 2018-05-16 12:57:00.956991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9234fff1ed1f'
down_revision = 'fe2ef0f61b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], )
    )
    op.drop_table('book_autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_autor',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='book_autor_author_id_fkey'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_autor_book_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'author_id', name='book_autor_pkey')
    )
    op.drop_table('association')
    # ### end Alembic commands ###
