"""add delete orphan

Revision ID: d305912758c4
Revises: 9234fff1ed1f
Create Date: 2018-05-17 11:45:55.962492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd305912758c4'
down_revision = '9234fff1ed1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
